$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'PaintHTML'
  app.device_family = [:iphone, :ipad]
  app.info_plist['UIStatusBarStyle'] = 'UIStatusBarStyleBlackTranslucent'
end
