# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/android'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'States'
  app.main_activity = 'MainActivity'
  app.sub_activities += %w(WikipediaActivity)
  app.permissions = 'android.permission.INTERNET'
end
