# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/osx'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'FlickrBrowser'
  app.frameworks += ['Quartz', 'PubSub']
  app.info_plist['NSAppTransportSecurity'] = {
    'NSExceptionDomains' => {
      'flickr.com' => {
        'NSTemporaryExceptionAllowsInsecureHTTPLoads' => true,
        'NSIncludesSubdomains' => true
      },
      'staticflickr.com' => {
        'NSTemporaryExceptionAllowsInsecureHTTPLoads' => true,
        'NSIncludesSubdomains' => true
      }
    }
  }
end
