# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/osx'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'Scenario'
  app.frameworks += %W[OpenGL SceneKit ApplicationServices QuartzCore CoreGraphics]
end
