$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'Reddit Search'
  app.info_plist['NSAppTransportSecurity'] = {
    'NSExceptionDomains' => {
      'www.reddit.com' => { 'NSTemporaryExceptionAllowsInsecureHTTPLoads' => true }
    }
  }
end
