# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/osx'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'Markdown'
  app.frameworks << 'WebKit'
  app.archs['MacOSX'] = ['x86_64']
  app.vendor_project('vendor/GHMarkdownParser', :static)
end
