# -*- coding: utf-8 -*-
$:.unshift("/Users/lrz/src/RubyMotionPrivate/lib")#Library/RubyMotion/lib")
require 'motion/project'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'CircleLayout'
  app.deployment_target = '6.0'
  app.entitlements['get-task-allow'] = true
end
