$:.unshift("/Library/Motion/lib")
require 'motion/project'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'trollify'
  app.frameworks += ['QuartzCore', 'AssetsLibrary', 'MobileCoreServices']
  app.icons = ['icon.png', 'icon@2x.png']
end
