# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  # app.delegate_class = 'Escape::AppDelegate'
  app.name = 'Escape'
  app.frameworks += %W{SpriteKit}
  app.files += Dir.glob(File.join(File.dirname(__FILE__), '../app/**/*.rb'))
  app.resources_dirs << '../resources'

  app.info_plist['UIStatusBarHidden'] = true

  app.info_plist['UISupportedInterfaceOrientations~ipad'] = [
    'UIInterfaceOrientationPortrait',
    'UIInterfaceOrientationPortraitUpsideDown',
    'UIInterfaceOrientationLandscapeLeft',
    'UIInterfaceOrientationLandscapeRight',
  ]

  app.info_plist['UISupportedInterfaceOrientations'] = [
    'UIInterfaceOrientationPortrait',
    'UIInterfaceOrientationPortraitUpsideDown',
  ]
  
  app.info_plist['UIViewControllerBasedStatusBarAppearance'] = false
end
